/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-25 04:54:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1666402150834L));
    _jspx_dependants.put("jar:file:/C:/SpringProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/myProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- css js 안먹히는 것 해결용 -->\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>NAVER LOGIN TEST</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- added -->\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("        <!-- Favicon-->\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"/resources/assets/favicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--inserted part-->\r\n");
      out.write("        <!-- Latest compiled and minified CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("        <!-- jQuery library -->\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("        <!-- Popper JS -->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("        <!-- Latest compiled JavaScript -->\r\n");
      out.write("        <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script></head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v6.1.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Alkalami&family=Noto+Serif+Telugu:wght@500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link  rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/styles.css\"/>\r\n");
      out.write("        <style>\r\n");
      out.write("        .carousel-inner{\r\n");
      out.write("            display : block;\r\n");
      out.write("\r\n");
      out.write("          }\r\n");
      out.write("        .carousel-item{\r\n");
      out.write("            text-align : center;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-contorl-prev-icon{\r\n");
      out.write("            visibility: visible;\r\n");
      out.write("        }\r\n");
      out.write("        </style>\r\n");
      out.write("        \r\n");
      out.write("    <!-- added end -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!--  added -->\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("        <!-- Navigation-->\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\" id=\"mainNav\">\r\n");
      out.write("\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#page-top\">\r\n");
      out.write("                    <!--<img src=\"assets/img/navbar-logo.svg\" alt=\"...\" />-->\r\n");
      out.write("                    HanGeulYi-Lang\r\n");
      out.write("                </a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    Menu\r\n");
      out.write("                    <i class=\"fas fa-bars ms-1\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("                    <ul class=\"navbar-nav text-uppercase ms-auto py-4 py-lg-0\">\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#services\">Services</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#portfolio\">More Details</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#about\">About</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#team\">Team</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#contact\">Contact</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"login.html\" target=\"_blank\">Login</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"register.html\" target=\"_blank\">Register</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"forgot-password.html\" target=\"_blank\">Forgot Password</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- Masthead-->\r\n");
      out.write("        <header class=\"masthead\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"masthead-subheading\">Welcome To HanGeulYi-Lang Dictionary!</div>\r\n");
      out.write("                <div class=\"masthead-heading text-uppercase\">It's Pleasure to Meet YOU</div>\r\n");
      out.write("                <a class=\"btn btn-primary btn-xl text-uppercase\" href=\"#services\">About ME</a>\r\n");
      out.write("                <div class=\"container position-relative\">\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-xl-6\">\r\n");
      out.write("                        <div class=\"text-center text-white\">\r\n");
      out.write("                            <!-- Page heading-->\r\n");
      out.write("                            <h1 class=\"mb-5\">Straight into What You Want!</h1>\r\n");
      out.write("                            <!-- Signup form-->\r\n");
      out.write("                            <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                            <!-- * * SB Forms Contact Form * *-->\r\n");
      out.write("                            <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                            <!-- This form is pre-integrated with SB Forms.-->\r\n");
      out.write("                            <!-- To make this form functional, sign up at-->\r\n");
      out.write("                            <!-- https://startbootstrap.com/solution/contact-forms-->\r\n");
      out.write("                            <!-- to get an API token!-->\r\n");
      out.write("                            <form class=\"form-subscribe\" id=\"contactForm\">\r\n");
      out.write("                                <!-- Email address input-->\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col\">\r\n");
      out.write("                                        <input class=\"form-control form-control-lg\" id=\"target_word\" type=\"text\" placeholder=\"ex)사과\" />\r\n");
      out.write("                                        <div class=\"invalid-feedback text-white\">Any word is required.</div>\r\n");
      out.write("                                        <div class=\"invalid-feedback text-white\">The word format is not valid.</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-auto\"><button class=\"btn btn-primary btn-lg disabled\" id=\"submitButton\" type=\"submit\">검색</button></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Submit success message-->\r\n");
      out.write("                                <!---->\r\n");
      out.write("                                <!-- This is what your users will see when the form-->\r\n");
      out.write("                                <!-- has successfully submitted-->\r\n");
      out.write("                                <div class=\"d-none\" id=\"submitSuccessMessage\">\r\n");
      out.write("                                    <div class=\"text-center mb-3\">\r\n");
      out.write("                                        <div class=\"fw-bolder\">Form submission successful!</div>\r\n");
      out.write("                                        <p>To activate this form, sign up at</p>\r\n");
      out.write("                                        <a class=\"text-white\" href=\"https://startbootstrap.com/solution/contact-forms\">https://startbootstrap.com/solution/contact-forms</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Submit error message-->\r\n");
      out.write("                                <!---->\r\n");
      out.write("                                <!-- This is what your users will see when there is-->\r\n");
      out.write("                                <!-- an error submitting the form-->\r\n");
      out.write("                                <div class=\"d-none\" id=\"submitErrorMessage\"><div class=\"text-center text-danger mb-3\">Error sending message!</div></div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- Services-->\r\n");
      out.write("        <section class=\"page-section\" id=\"services\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">Services</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">These are the information about MYSELF!</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row text-center\">\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <span class=\"fa-stack fa-4x\">\r\n");
      out.write("                            <i class=\"fas fa-square fa-stack-2x text-primary\"></i>\r\n");
      out.write("                            <i class=\"fas fa-person fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("                            <!--  내부 색상 반전  fa-inverse  -->\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <h4 class=\"my-3\">Intorduction</h4>\r\n");
      out.write("                        <p class=\"text-muted\">Hi. This is our first mini web programming project for beginners learning Korean. Hope you enjoy our page!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <span class=\"fa-stack fa-4x\">\r\n");
      out.write("                            <i class=\"fas fa-star fa-stack-2x text-primary\"></i>\r\n");
      out.write("                            <i class=\"fas fa-laptop fa-stack-1x\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <h4 class=\"my-3\">The projects</h4>\r\n");
      out.write("                        <p class=\"text-muted\">The project lasted 6 days, based on Spring framework using HTML, CSS, Javascript using GitHub platform!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <span class=\"fa-stack fa-4x\">\r\n");
      out.write("                            <i class=\"fas fa-circle fa-stack-2x text-primary\"></i>\r\n");
      out.write("                            <i class=\"fas fa-plus fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <h4 class=\"my-3\">Ability</h4>\r\n");
      out.write("                        <p class=\"text-muted\">Still<br> Kind<br> Easy</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Portfolio Grid-->\r\n");
      out.write("        <section class=\"page-section bg-light\" id=\"portfolio\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">More Details</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">These are what I have done.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12 offset-md-1\">\r\n");
      out.write("                <!-- 캐러셀 시작----------------------- -->\r\n");
      out.write("                <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\" data-interval=\"2000\">\r\n");
      out.write("                    <!-- data-interval=\"4000\"으로 주면 4초마다 자동으로 슬라이딩 된다. -->\r\n");
      out.write("                    <!-- Indicator (사진 목록 표시자)-->\r\n");
      out.write("                    <ul class=\"carousel-indicators\">\r\n");
      out.write("                        <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                        <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("                        <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("                        <li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- Slideshow -->\r\n");
      out.write("                    <div class=\"carousel-inner\">\r\n");
      out.write("                        <div class=\"carousel-item active\">                    \r\n");
      out.write("                            <img src=\"resources/assets/img/portfolio/world-language.jpg\"  class=\"img-fluid\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"carousel-item\">                    \r\n");
      out.write("                            <img src=\"resources/assets/img/portfolio/book.jfif\"   class=\"img-fluid\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"carousel-item\">                    \r\n");
      out.write("                            <img src=\"resources/assets/img/portfolio/yoga.jpg\"   class=\"img-fluid\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"carousel-item\">                    \r\n");
      out.write("                            <img src=\"resources/assets/img/portfolio/thinking.png\"  class=\"img-fluid\">\r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("                    </div>\r\n");
      out.write("        \r\n");
      out.write("                    <!-- Left/Right Control -->\r\n");
      out.write("                    <a href=\"#myCarousel\" class=\"carousel-control-prev\" data-slide=\"prev\">\r\n");
      out.write("                        <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#myCarousel\" class=\"carousel-control-next\" data-slide=\"next\">\r\n");
      out.write("                        <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- --------------------------------- -->\r\n");
      out.write("                </div>  <!-- col end-->\r\n");
      out.write("                </div> <!-- row end-->\r\n");
      out.write("\r\n");
      out.write("                <br><br><br>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4\">\r\n");
      out.write("                        <!-- Portfolio item 1-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal1\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"resources/assets/img/portfolio/world-language.jpg\" alt=\"...\" height=\"60px\"/>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Language</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">HARD TO LEARN</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4\">\r\n");
      out.write("                        <!-- Portfolio item 2-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal2\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"resources/assets/img/portfolio/book.jfif\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Book</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">TOO HEAVY</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4\">\r\n");
      out.write("                        <!-- Portfolio item 3-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal3\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"resources/assets/img/portfolio/yoga.jpg\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Health</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Identity</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4 mb-lg-0\">\r\n");
      out.write("                        <!-- Portfolio item 4-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal4\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"resources/assets/img/portfolio/thinking.png\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Mind</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Keep motivating with various fields</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4 mb-sm-0\">\r\n");
      out.write("                        <!-- Portfolio item 5-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal5\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"resources/assets/img/portfolio/5.jpg\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Southwest</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Website Design</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                        <!-- Portfolio item 6-->\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal6\">\r\n");
      out.write("                                <div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"resources/assets/img/portfolio/6.jpg\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Window</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Photography</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- About-->\r\n");
      out.write("        <section class=\"page-section\" id=\"about\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">About CS Career</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Lorem ipsum dolor sit amet consectetur.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"timeline\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"resources/assets/img/about/1.jpg\" alt=\"...\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>2020-2025</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">Majorying Computer Science</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">While studying enourmously various subjects, I am interested in Back-end part. Also, I wanted to study more about BigData and AI.</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"timeline-inverted\">\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"resources/assets/img/about/2.jpg\" alt=\"...\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>August 2022</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">Full-stacking</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">It was a quite fabulous experience.</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"resources/assets/img/about/3.jpg\" alt=\"...\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>December 2015</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">Transition to Full Service</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"timeline-inverted\">\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"resources/assets/img/about/4.jpg\" alt=\"...\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>July 2020</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">Phase Two Expansion</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"timeline-inverted\">\r\n");
      out.write("                        <div class=\"timeline-image\">\r\n");
      out.write("                            <h4>\r\n");
      out.write("                                Be Part\r\n");
      out.write("                                <br />\r\n");
      out.write("                                Of Our\r\n");
      out.write("                                <br />\r\n");
      out.write("                                Story!\r\n");
      out.write("                            </h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Team-->\r\n");
      out.write("        <section class=\"page-section bg-light\" id=\"team\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">Our Amazing Team</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Lorem ipsum dolor sit amet consectetur.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"team-member\">\r\n");
      out.write("                            <img class=\"mx-auto rounded-circle\" src=\"resources/assets/img/team/1.jpg\" alt=\"...\" />\r\n");
      out.write("                            <h4>Parveen Anand</h4>\r\n");
      out.write("                            <p class=\"text-muted\">Lead Designer</p>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Parveen Anand Twitter Profile\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Parveen Anand Facebook Profile\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Parveen Anand LinkedIn Profile\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"team-member\">\r\n");
      out.write("                            <img class=\"mx-auto rounded-circle\" src=\"resources/assets/img/team/2.jpg\" alt=\"...\" />\r\n");
      out.write("                            <h4>Diana Petersen</h4>\r\n");
      out.write("                            <p class=\"text-muted\">Lead Marketer</p>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Diana Petersen Twitter Profile\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Diana Petersen Facebook Profile\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Diana Petersen LinkedIn Profile\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"team-member\">\r\n");
      out.write("                            <img class=\"mx-auto rounded-circle\" src=\"resources/assets/img/team/3.jpg\" alt=\"...\" />\r\n");
      out.write("                            <h4>Larry Parker</h4>\r\n");
      out.write("                            <p class=\"text-muted\">Lead Developer</p>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Larry Parker Twitter Profile\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Larry Parker Facebook Profile\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Larry Parker LinkedIn Profile\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-8 mx-auto text-center\"><p class=\"large text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Clients-->\r\n");
      out.write("        <div class=\"py-5\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"https://www.microsoft.com/\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"resources/assets/img/logos/microsoft.svg\" alt=\"...\" aria-label=\"Microsoft Logo\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"https://www.google.co.kr/?gws_rd=ssl\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"resources/assets/img/logos/google.svg\" alt=\"...\" aria-label=\"Google Logo\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"https://www.facebook.com/\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"resources/assets/img/logos/facebook.svg\" alt=\"...\" aria-label=\"Facebook Logo\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"https://www.ibm.com/ibm/homepage\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"resources/assets/img/logos/ibm.svg\" alt=\"...\" aria-label=\"IBM Logo\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Contact-->\r\n");
      out.write("        <section class=\"page-section\" id=\"contact\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">Contact Us</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Lorem ipsum dolor sit amet consectetur.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                <!-- * * SB Forms Contact Form * *-->\r\n");
      out.write("                <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                <!-- This form is pre-integrated with SB Forms.-->\r\n");
      out.write("                <!-- To make this form functional, sign up at-->\r\n");
      out.write("                <!-- https://startbootstrap.com/solution/contact-forms-->\r\n");
      out.write("                <!-- to get an API token!-->\r\n");
      out.write("                <form id=\"contactForm\" data-sb-form-api-token=\"API_TOKEN\">\r\n");
      out.write("                    <div class=\"row align-items-stretch mb-5\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <!-- Name input-->\r\n");
      out.write("                                <input class=\"form-control\" id=\"name\" type=\"text\" placeholder=\"Your Name *\" data-sb-validations=\"required\" />\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"name:required\">A name is required.</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <!-- Email address input-->\r\n");
      out.write("                                <input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"Your Email *\" data-sb-validations=\"required,email\" />\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"email:required\">An email is required.</div>\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"email:email\">Email is not valid.</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group mb-md-0\">\r\n");
      out.write("                                <!-- Phone number input-->\r\n");
      out.write("                                <input class=\"form-control\" id=\"phone\" type=\"tel\" placeholder=\"Your Phone *\" data-sb-validations=\"required\" />\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"phone:required\">A phone number is required.</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group form-group-textarea mb-md-0\">\r\n");
      out.write("                                <!-- Message input-->\r\n");
      out.write("                                <textarea class=\"form-control\" id=\"message\" placeholder=\"Your Message *\" data-sb-validations=\"required\"></textarea>\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"message:required\">A message is required.</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Submit success message-->\r\n");
      out.write("                    <!---->\r\n");
      out.write("                    <!-- This is what your users will see when the form-->\r\n");
      out.write("                    <!-- has successfully submitted-->\r\n");
      out.write("                    <div class=\"d-none\" id=\"submitSuccessMessage\">\r\n");
      out.write("                        <div class=\"text-center text-white mb-3\">\r\n");
      out.write("                            <div class=\"fw-bolder\">Form submission successful!</div>\r\n");
      out.write("                            To activate this form, sign up at\r\n");
      out.write("                            <br />\r\n");
      out.write("                            <a href=\"https://startbootstrap.com/solution/contact-forms\">https://startbootstrap.com/solution/contact-forms</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Submit error message-->\r\n");
      out.write("                    <!---->\r\n");
      out.write("                    <!-- This is what your users will see when there is-->\r\n");
      out.write("                    <!-- an error submitting the form-->\r\n");
      out.write("                    <div class=\"d-none\" id=\"submitErrorMessage\"><div class=\"text-center text-danger mb-3\">Error sending message!</div></div>\r\n");
      out.write("                    <!-- Submit Button-->\r\n");
      out.write("                    <div class=\"text-center\"><button class=\"btn btn-primary btn-xl text-uppercase disabled\" id=\"submitButton\" type=\"submit\">Send Message</button></div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer py-4\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-lg-4 text-lg-start\">Copyright &copy; Your Website 2022</div>\r\n");
      out.write("                    <div class=\"col-lg-4 my-3 my-lg-0\">\r\n");
      out.write("                        <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Twitter\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"Facebook\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\" aria-label=\"LinkedIn\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 text-lg-end\">\r\n");
      out.write("                        <a class=\"link-dark text-decoration-none me-3\" href=\"#!\">Privacy Policy</a>\r\n");
      out.write("                        <a class=\"link-dark text-decoration-none\" href=\"#!\">Terms of Use</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Portfolio Modals-->\r\n");
      out.write("        <!-- Portfolio item 1 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"resources/assets/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Language</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">These are the languages what I have learnt.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/world-language.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Korean : Native Speaker<br>\r\n");
      out.write("                                    English : TOEIC 850 Advanced Low No barrier for Working<br>\r\n");
      out.write("                                    Chinese : HSK Level 5 Intermediate High<br>\r\n");
      out.write("                                    Russian : Beginner<br>\r\n");
      out.write("                                    Arabic : Beginner</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Threads\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Illustration\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Language\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio item 2 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/2.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Explore\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Graphic Design\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Project\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio item 3 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/3.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Finish\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Identity\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Project\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio item 4 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/4.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Lines\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Branding\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Project\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio item 5 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/5.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Southwest\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Website Design\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Project\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio item 6 modal popup-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project details-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/6.jpg\" alt=\"...\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Client:</strong>\r\n");
      out.write("                                            Window\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong>Category:</strong>\r\n");
      out.write("                                            Photography\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark me-1\"></i>\r\n");
      out.write("                                        Close Project\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("//js/scripts.js\"></script>\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <!-- * *                               SB Forms JS                               * *-->\r\n");
      out.write("        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- added end -->\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /index.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /index.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
